-- Starter schema. Review and test policies before using real student data.
create extension if not exists pgcrypto;
create table teams (id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null);
create table profiles (id uuid primary key references auth.users(id) on delete cascade, team_id uuid not null references teams(id), display_name text not null, role text not null check (role in ('student','parent','coach')), linked_student_id uuid references profiles(id), is_active boolean not null default true);
create table assignments (id uuid primary key default gen_random_uuid(), team_id uuid not null references teams(id), title text not null, description text not null, due_at timestamptz, created_by uuid references profiles(id), created_at timestamptz not null default now());
create table submissions (id uuid primary key default gen_random_uuid(), assignment_id uuid not null references assignments(id), student_id uuid not null references profiles(id), response_text text, status text not null default 'submitted' check(status in ('assigned','submitted','review','revise','complete')), score numeric, coach_feedback text, created_at timestamptz not null default now());
create table questions (id uuid primary key default gen_random_uuid(), team_id uuid not null references teams(id), author_id uuid not null references profiles(id), question text not null, ai_answer text, coach_answer text, visibility text not null default 'team' check(visibility in ('private','team','public')), moderation_status text not null default 'pending', created_at timestamptz not null default now());
create table coding_projects (id uuid primary key default gen_random_uuid(), team_id uuid not null references teams(id), owner_id uuid not null references profiles(id), title text not null, visibility text not null default 'team', created_at timestamptz not null default now());
create table coding_versions (id uuid primary key default gen_random_uuid(), project_id uuid not null references coding_projects(id) on delete cascade, version_number integer not null, html text not null default '', css text not null default '', javascript text not null default '', reflection text not null default '', created_at timestamptz not null default now(), unique(project_id,version_number));
create table robot_tests (id uuid primary key default gen_random_uuid(), team_id uuid not null references teams(id), author_id uuid not null references profiles(id), mission text not null, attempts integer not null check(attempts > 0), successes integer not null check(successes between 0 and attempts), next_change text, created_at timestamptz not null default now());
alter table profiles enable row level security; alter table assignments enable row level security; alter table submissions enable row level security; alter table questions enable row level security; alter table coding_projects enable row level security; alter table coding_versions enable row level security; alter table robot_tests enable row level security;
-- Deliberately deny access until project-specific, role-tested RLS policies are installed.
