alter table assignments add column if not exists week_number integer;
alter table assignments add column if not exists published boolean not null default false;
alter table submissions add column if not exists submitted_at timestamptz;
create unique index if not exists assignments_team_week_key on assignments(team_id,week_number) where week_number is not null;
create unique index if not exists submissions_assignment_student_key on submissions(assignment_id,student_id);
create table if not exists assignment_questions(id uuid primary key default gen_random_uuid(),assignment_id uuid not null references assignments(id) on delete cascade,question_key text not null,display_order integer not null default 0,prompt text not null,answer_type text not null check(answer_type in ('text','long_text','single_choice','multiple_choice','file')),options jsonb,required boolean not null default true,unique(assignment_id,question_key));
create table if not exists submission_answers(id uuid primary key default gen_random_uuid(),submission_id uuid not null references submissions(id) on delete cascade,question_key text not null,display_order integer not null default 0,answer_type text not null,answer_text text,answer_json jsonb,unique(submission_id,question_key));
create table if not exists submission_files(id uuid primary key default gen_random_uuid(),submission_id uuid not null references submissions(id) on delete cascade,file_name text not null,storage_path text unique not null,mime_type text not null,size_bytes bigint not null check(size_bytes between 1 and 8388608),uploaded_by uuid not null references profiles(id),created_at timestamptz not null default now());
alter table assignment_questions enable row level security;alter table submission_answers enable row level security;alter table submission_files enable row level security;
create policy assignment_questions_team_read on assignment_questions for select using(exists(select 1 from assignments a where a.id=assignment_id and a.team_id=current_team_id()));
create policy submission_answers_read on submission_answers for select using(exists(select 1 from submissions s where s.id=submission_id));
create policy submission_answers_add on submission_answers for insert with check(exists(select 1 from submissions s where s.id=submission_id and (s.student_id=auth.uid() or current_profile_role()='coach')));
create policy submission_answers_update on submission_answers for update using(exists(select 1 from submissions s where s.id=submission_id and (s.student_id=auth.uid() or current_profile_role()='coach'))) with check(exists(select 1 from submissions s where s.id=submission_id and (s.student_id=auth.uid() or current_profile_role()='coach')));
create policy submission_files_read on submission_files for select using(exists(select 1 from submissions s where s.id=submission_id));
create policy submission_files_add on submission_files for insert with check(uploaded_by=auth.uid() and exists(select 1 from submissions s where s.id=submission_id and s.student_id=auth.uid()));
create policy submission_student_update on submissions for update using(student_id=auth.uid() and current_profile_role()='student') with check(student_id=auth.uid() and current_profile_role()='student');
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('homework-files','homework-files',false,8388608,array['image/jpeg','image/png','image/webp','application/pdf']) on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy homework_file_read on storage.objects for select to authenticated using(bucket_id='homework-files' and can_manage_student(((storage.foldername(name))[1])::uuid));
create policy homework_file_add on storage.objects for insert to authenticated with check(bucket_id='homework-files' and auth.uid()=((storage.foldername(name))[1])::uuid);
insert into assignments(team_id,title,description,due_at,created_by,week_number,published)
select t.id,'Explore biodiversity','Watch the introduction video, research one biodiversity topic, write a paragraph about what interests you, and watch the 2026 FLL season reveal on August 4 at 9:00 AM Pacific.','2026-08-07 17:00:00-07',p.id,0,true from teams t join profiles p on p.team_id=t.id and p.role='coach' and p.approval_status='approved' where t.slug='folsom-fireflies' order by p.approved_at limit 1
on conflict(team_id,week_number) where week_number is not null do update set title=excluded.title,description=excluded.description,due_at=excluded.due_at,published=true;
insert into assignment_questions(assignment_id,question_key,display_order,prompt,answer_type,required)
select a.id,q.key,q.ord,q.prompt,q.kind,q.required from assignments a cross join (values('topic',0,'What biodiversity topic did you choose?','text',true),('paragraph',1,'What interests you about it?','long_text',true),('sources',2,'What sources or links did you use?','long_text',false)) q(key,ord,prompt,kind,required) where a.team_id=(select id from teams where slug='folsom-fireflies') and a.week_number=0
on conflict(assignment_id,question_key) do update set prompt=excluded.prompt,answer_type=excluded.answer_type,required=excluded.required;
